spring.application.name=api-gateway
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=false

# Doctor Service
spring.cloud.gateway.routes[0].id=doctor
spring.cloud.gateway.routes[0].uri=lb://doctor
spring.cloud.gateway.routes[0].predicates[0]=Path=/doctor/**

# Patient Service
spring.cloud.gateway.routes[1].id=patient
spring.cloud.gateway.routes[1].uri=lb://patient
spring.cloud.gateway.routes[1].predicates[0]=Path=/patient/**